const COUNT = 'COUNT';
const ISEVENORODD = 'ISEVENORODD';
const INCREMENT = 'INCREMENT';
const DECREASE = 'DECREASE';
const INCREMENTASYNC = 'INCREMENTASYNC';

export default {
  COUNT,
  ISEVENORODD,
  INCREMENT,
  DECREASE,
  INCREMENTASYNC
}
